import Foundation
import Testing
@testable import ZenAgent

@Suite("Surface Lift presentation state")
struct SurfaceLiftStateTests {
    @Test func longPressOnlyArmsAndReleaseStaysFull() {
        var state = SurfaceLiftState()
        let arm1 = state.arm(SurfaceLiftEligibility())
        #expect(arm1)
        #expect(state.phase == .armed)
        #expect(state.progress == 0)
        let arm2 = state.arm(SurfaceLiftEligibility())
        #expect(!arm2)
        let end1 = state.end()
        #expect(end1 == nil)
        #expect(state.phase == .full && state.progress == 0)
    }

    @Test func dragOnsetDirectionBacktrackAndCommit() throws {
        var state = SurfaceLiftState()
        let arm3 = state.arm(SurfaceLiftEligibility())
        #expect(arm3)
        let drag1 = state.drag(upwardDistance: -40, eligibility: SurfaceLiftEligibility())
        #expect(drag1)
        #expect(state.phase == .armed && state.progress == 0)
        let drag2 = state.drag(upwardDistance: 11, eligibility: SurfaceLiftEligibility())
        #expect(drag2)
        #expect(state.phase == .armed)
        let drag3 = state.drag(upwardDistance: 96, eligibility: SurfaceLiftEligibility())
        #expect(drag3)
        #expect(state.phase == .lifting && state.progress == 0.5)
        let drag4 = state.drag(upwardDistance: 40, eligibility: SurfaceLiftEligibility())
        #expect(drag4)
        #expect(abs(state.progress - 1.0 / 6.0) < 0.000001)
        let drag5 = state.drag(upwardDistance: 300, eligibility: SurfaceLiftEligibility())
        #expect(drag5)
        #expect(state.progress == 1)
        let end2 = state.end()
        let settle = try #require(end2)
        #expect(settle.destination == .card && settle.startProgress == 1)
        #expect(state.phase == .settling)
        let complete1 = state.complete(settle, finished: true)
        #expect(complete1)
        #expect(state.phase == .card && state.progress == 1)
    }

    @Test(arguments: [false, true])
    func cancellationOrShortDragReturnsFull(cancelled: Bool) throws {
        var state = SurfaceLiftState()
        let arm4 = state.arm(SurfaceLiftEligibility())
        #expect(arm4)
        let drag6 = state.drag(upwardDistance: cancelled ? 180 : 40, eligibility: SurfaceLiftEligibility())
        #expect(drag6)
        let end3 = state.end(cancelled: cancelled)
        let settle = try #require(end3)
        #expect(settle.destination == .full)
        let complete2 = state.complete(settle, finished: true)
        #expect(complete2)
        #expect(state.phase == .full && state.progress == 0)
    }

    @Test func everyUnsafeInputBlocksArmingAndInterruptsDrag() {
        var inputs = [SurfaceLiftEligibility]()
        var editing = SurfaceLiftEligibility(); editing.isEditing = true; inputs.append(editing)
        var composing = SurfaceLiftEligibility(); composing.hasMarkedText = true; inputs.append(composing)
        var visible = SurfaceLiftEligibility(); visible.keyboardVisible = true; inputs.append(visible)
        var changing = SurfaceLiftEligibility(); changing.keyboardTransitioning = true; inputs.append(changing)
        var moving = SurfaceLiftEligibility(); moving.composerSettled = false; inputs.append(moving)
        var selected = SurfaceLiftEligibility(); selected.selectionActive = true; inputs.append(selected)
        var quote = SurfaceLiftEligibility(); quote.quoteDragActive = true; inputs.append(quote)
        var overlay = SurfaceLiftEligibility(); overlay.overlayPresented = true; inputs.append(overlay)
        for input in inputs {
            var state = SurfaceLiftState()
            #expect(!input.allowsLift)
            let arm5 = state.arm(input)
            #expect(!arm5)
            #expect(state.phase == .full && state.progress == 0)
            let arm6 = state.arm(SurfaceLiftEligibility())
            #expect(arm6)
            let drag7 = state.drag(upwardDistance: 96, eligibility: SurfaceLiftEligibility())
            #expect(drag7)
            let drag8 = state.drag(upwardDistance: 110, eligibility: input)
            #expect(!drag8)
            #expect(state.phase == .full && state.progress == 0)
        }
    }

    @Test func invalidMotionCannotCorruptState() {
        var state = SurfaceLiftState()
        let drag9 = state.drag(upwardDistance: 96, eligibility: SurfaceLiftEligibility())
        #expect(!drag9)
        let arm7 = state.arm(SurfaceLiftEligibility())
        #expect(arm7)
        let drag10 = state.drag(upwardDistance: 96, eligibility: SurfaceLiftEligibility())
        #expect(drag10)
        let before = state
        let drag11 = state.drag(upwardDistance: .nan, eligibility: SurfaceLiftEligibility())
        #expect(!drag11)
        let drag12 = state.drag(upwardDistance: .infinity, eligibility: SurfaceLiftEligibility())
        #expect(!drag12)
        #expect(state == before)
        let requestReturn1 = state.requestReturn(visibleProgress: .nan)
        #expect(requestReturn1 == nil)
        #expect(state == before)
    }

    @Test func returnUsesVisibleProgressAndRejectsLateCompletion() throws {
        var state = SurfaceLiftState()
        let arm8 = state.arm(SurfaceLiftEligibility())
        #expect(arm8)
        let drag13 = state.drag(upwardDistance: 130, eligibility: SurfaceLiftEligibility())
        #expect(drag13)
        let end4 = state.end()
        let old = try #require(end4)
        let requestReturn2 = state.requestReturn(visibleProgress: 0.8)
        let returning = try #require(requestReturn2)
        #expect(returning.destination == .full && returning.startProgress == 0.8)
        #expect(returning.identity != old.identity)
        let before = state
        let complete3 = state.complete(old, finished: true)
        #expect(!complete3)
        #expect(state == before)
        let complete4 = state.complete(returning, finished: true)
        #expect(complete4)
        #expect(state.phase == .full && state.progress == 0)
        let arm9 = state.arm(SurfaceLiftEligibility())
        #expect(arm9)
        let complete5 = state.complete(returning, finished: true)
        #expect(!complete5)
        #expect(state.phase == .armed)
    }

    @Test func acceptedSplitSettlesSeparatelyFromCardAndCanReturn() throws {
        var state = SurfaceLiftState()
        let armed = state.arm(SurfaceLiftEligibility())
        #expect(armed)
        let dragged = state.drag(upwardDistance: 320, eligibility: SurfaceLiftEligibility())
        #expect(dragged)
        let splitResult = state.endForSplit()
        let split = try #require(splitResult)
        #expect(split.destination == .split)
        let completed = state.complete(split, finished: true)
        #expect(completed)
        #expect(state.phase == .split && state.progress == 1)
        let returnResult = state.requestReturn(visibleProgress: 0.8)
        let returning = try #require(returnResult)
        #expect(returning.destination == .full && returning.startProgress == 0.8)
        let staleCompletion = state.complete(split, finished: true)
        #expect(!staleCompletion)
        let returned = state.complete(returning, finished: true)
        #expect(returned)
        #expect(state.phase == .full && state.progress == 0)
    }

    @Test func interruptAndUnfinishedCompletionCannotLeaveStuckPresentation() throws {
        var state = SurfaceLiftState()
        let arm10 = state.arm(SurfaceLiftEligibility())
        #expect(arm10)
        let drag14 = state.drag(upwardDistance: 180, eligibility: SurfaceLiftEligibility())
        #expect(drag14)
        let end5 = state.end()
        let old = try #require(end5)
        state.interrupt()
        let complete6 = state.complete(old, finished: true)
        #expect(!complete6)
        #expect(state.phase == .full && state.pendingSettlement == nil)
        let arm11 = state.arm(SurfaceLiftEligibility())
        #expect(arm11)
        let drag15 = state.drag(upwardDistance: 180, eligibility: SurfaceLiftEligibility())
        #expect(drag15)
        let end6 = state.end()
        let next = try #require(end6)
        let complete7 = state.complete(next, finished: false)
        #expect(complete7)
        #expect(state.phase == .full && state.progress == 0 && state.pendingSettlement == nil)
    }
}
